default_language_version:
  python: python3
repos:
  - repo: https://github.com/psf/black
    rev: "23.11.0"
    hooks:
      - id: black
        args: [ --config=.precommit.toml ]
        types: [ python ]
  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: [ --settings-file=.precommit.toml ]
        types: [ python ]
  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        types: [ python ]
        args: [--max-line-length=100]
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ --in-place, --expand-star-imports, --remove-duplicate-keys, --ignore-init-module-imports, --remove-all-unused-imports ]
        types: [ python ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-toml
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-xml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: mixed-line-ending
        args: [ --fix=lf ]
        files: '\.(py|cpp|hpp|c|h)$'